package com.javalearning.OOP.ExceptionHandling;

public class ExceptionIntro {

	public static void main(String[] args) {
		int arr[] = {21,22,23};
		//System.out.println(arr[3]);//program terminated
		System.out.println("After accessing array element");

	}

}
